sonar.projectKey=15soat-tech-challenge-step-1
sonar.projectName=15soat Tech Challenge Step 1
sonar.projectVersion=1.0

sonar.sourceEncoding=UTF-8
sonar.sources=cmd,database,internal,packages
sonar.tests=cmd,database,internal,packages
sonar.test.inclusions=**/*_test.go

sonar.exclusions=web/**,**/*_test.go,.git/**,.scannerwork/**,.vscode/**,internal/config/**,internal/database/**,internal/repository/**,database/**
sonar.coverage.exclusions=cmd/**,database/**,**/*_test.go
sonar.go.coverage.reportPaths=coverage.out

