apiVersion: v1
kind: Service
metadata:
  name: mailhog-service
  namespace: workshop
  labels:
    app.kubernetes.io/name: oficina-mecanica
    app.kubernetes.io/component: mail
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: oficina-mecanica
    app.kubernetes.io/component: mail
  ports:
    - name: smtp
      port: 1025
      targetPort: smtp
    - name: http
      port: 8025
      targetPort: http
