apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: workshop
  labels:
    app.kubernetes.io/name: oficina-mecanica
type: Opaque
stringData:
  DATABASE_PASSWORD: "<set-in-ci>"
  JWT_SECRET_KEY: "<set-in-ci>"
